Twist
Twist

diff --git a/twist b/twist
--- a/twist
+++ b/twist
@@ -1,6 +1,6 @@
 #! /bin/bash
 
-## Twist Ver 0.1.1 Written by Unbinilium https://github.com/Unbinilium/Twist
+## Twist Ver 0.1.2 Written by Unbinilium https://github.com/Unbinilium/Twist
 
 export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
 
@@ -409,10 +409,10 @@ function tcpbbrenable(){
         else
             echo "net.ipv4.tcp_congestion_control = hybla" >> /etc/sysctl.conf
             if grep -Eqi "Ubuntu|Arch Liunx|CentOS|Red Hat" /etc/*-release || grep -Eqi "Ubuntu|Arch Liunx|CentOS|Red Hat" /proc/version; then
-                updatekernel
+                kernelupdate
             else
                 echo ""
-                echo -e "# [\033[34;1mYou may Update Server Kernel and Enable BBR Manually. Aborting! \033[0m]"
+                echo -e "# [\033[34;1mYou may update server kernel and enable BBR manually. Aborting! \033[0m]"
                 BBR="disable"
                 sleep 3
             fi
@@ -420,34 +420,34 @@ function tcpbbrenable(){
     fi
 }
 
-function updatekernel(){
+function kernelupdate(){
     if [ "$packagemanagertype" = "a" ]; then
         KERNELURL="http://kernel.ubuntu.com/~kernel-ppa/mainline/"
         KERNELVER="$(wget -qO- ${KERNELURL} | awk -F'\"v' '/v[4-9]./{print $2}' | cut -d/ -f1 | grep -v -  | sort -V | tail -1)"
-        [ -z "$KERNELVER" ] && { BBR="disable"; echo -e "# [\033[31;1mCannot get the newest Linux Kernel Verison, BBR will not enable on your server! \033[0m]"; }
+        [ -z "$KERNELVER" ] && { BBR="disable"; echo -e "# [\033[31;1mCannot get the newest linux kernel verison, BBR will not enable on your server! \033[0m]"; }
         if [ "$BBR" = "enable" ]; then
             SYSTYPE="$(dpkg --print-architecture)"
             KERNEL="$(wget -qO- ${KERNELURL}v${KERNELVER}/ | grep "linux-image" | grep "generic" | awk -F'\">' '/${SYSTYPE}.deb/{print $2}' | cut -d'<' -f1 | head -1)"
             [ "$BBR" = "enable" ] && wget -t 3 -T 30 -nv -O "$KERNEL" "${KERNELURL}v${KERNELVER}/${KERNEL}"
-            [ "$BBR" = "enable" ] && { dpkg -i $KERNEL || { echo ""; echo -e "# [\033[31;1mCannot Update Kernel, BBR will not enable on your server! \033[0m]"; echo ""; sleep 3; BBR="disable"; }; }
+            [ "$BBR" = "enable" ] && { dpkg -i $KERNEL || { echo ""; echo -e "# [\033[31;1mCannot update kernel, BBR will not enable on your server! \033[0m]"; echo ""; sleep 3; BBR="disable"; }; }
             [ "$BBR" = "enable" ] && { dpkg -l | grep linux-image; rm -f $KERNEL; update-grub; }
         fi
     elif [ "$packagemanagertype" = "y" ]; then
-        rpm --import https://www.elrepo.org/RPM-GPG-KEY-elrepo.org || { echo ""; echo -e "# [\033[31;1mCannot Get ELRepo Key, you may unable to Install ELRepo Packages! \033[0m]"; echo ""; sleep 3; }
+        rpm --import https://www.elrepo.org/RPM-GPG-KEY-elrepo.org || { echo ""; echo -e "# [\033[31;1mCannot get ELRepo key, you may unable to install ELRepo packages! \033[0m]"; echo ""; sleep 3; }
         if grep -qs "release 7" /etc/*-release; then
-            rpm -Uvh $ELREPOVER7 || { echo ""; echo -e "# [\033[31;1mCannot Install ELRepo Repository. Aborting! \033[0m]"; echo ""; sleep 3; BBR="disable"; }
-            [ "$BBR" = "enable" ] && yum --enablerepo=elrepo-kernel -y install kernel-ml kernel-ml-devel || { echo ""; echo -e "# [\033[31;1mCannot Update Kernel, BBR will not enable on your server! \033[0m]"; echo ""; sleep 3; BBR="disable"; }
+            rpm -Uvh $ELREPOVER7 || { echo ""; echo -e "# [\033[31;1mCannot Install ELRepo repository. Aborting! \033[0m]"; echo ""; sleep 3; BBR="disable"; }
+            [ "$BBR" = "enable" ] && yum --enablerepo=elrepo-kernel -y install kernel-ml kernel-ml-devel || { echo ""; echo -e "# [\033[31;1mCannot update kernel, BBR will not enable on your server! \033[0m]"; echo ""; sleep 3; BBR="disable"; }
             [ "$BBR" = "enable" ] && grub2-set-default 0
         elif grep -qs "release 6" /etc/*-release; then
             rpm -Uvh $ELREPOVER6 || { echo ""; echo -e "# [\033[31;1mCannot Install ELRepo Repository. Aborting! \033[0m]"; echo ""; sleep 3; BBR="disable"; }
-            [ "$BBR" = "enable" ] && yum --enablerepo=elrepo-kernel -y install kernel-ml kernel-ml-devel || { echo ""; echo -e "# [\033[31;1mCannot Update Kernel, BBR will not enable on your server! \033[0m]"; echo ""; sleep 3; BBR="disable"; }
+            [ "$BBR" = "enable" ] && yum --enablerepo=elrepo-kernel -y install kernel-ml kernel-ml-devel || { echo ""; echo -e "# [\033[31;1mCannot update kernel, BBR will not enable on your server! \033[0m]"; echo ""; sleep 3; BBR="disable"; }
             [ "$BBR" = "enable" ] && sed -i 's/^default=.*/default=0/g' /boot/grub/grub.conf
         fi
     elif [ "$packagemanagertype" = "p" ]; then
         if grep -Eqi "IgnorePkg|IgnoreGroup" /etc/pacman.conf; then
             sed -i "/IgnorePkg/d;/IgnoreGroup/d" /etc/pacman.conf
         fi
-        pacman -Syyu --noconfirm || { echo ""; echo -e "# [\033[31;1mCannot Update Kernel and Sources, BBR will not enable on your server! \033[0m]"; echo ""; sleep 3; BBR="disable"; }
+        pacman -Syyu --noconfirm || { echo ""; echo -e "# [\033[31;1mCannot update kernel and sources, BBR will not enable on your server! \033[0m]"; echo ""; sleep 3; BBR="disable"; }
     fi
     [ "$BBR" = "enable" ] && { kernelupdated="true"; serverrestart="true"; }
     kernelverheader="$(uname -r | grep -oE '[0-9]+\.[0-9]+')"
